### ISSUE TITLE
一个错误

### ISSUE THREAD

**Issue by yanxyz** [gf-web/es6-coding-style#4]
”箭头函数必须与左右保持两个空格间距“，这句是说错了吧？本意是想说 ”箭头左右放一个空格“？实际上文章内不少重复的地方可以总结为一句话：所有的关键字，操作符左右放一个空格。

 5.1 示例：

```js
// 不好
const foo = function(x) {
  console.log('存在函数提升问题');
  console.log(foo.name); // 返回'' ，函数表达式不可命名，函数声明可以
};
```

第一个问题，这个示例不存在函数提升问题。

第二个问题，提到函数表达式不可命名，这是错的。

示例用的是匿名函数，改成具名函数：

```js
const foo = function foo(x) {
  console.log(foo.name); // ?
};
```

现在 "="  右边仍然是一个函数表达式，但是有名字，看起来跟函数声明式一模一样。函数表达式与函数声明式由它们的位置区分。

上面说的是 ES5。如果是 ES6 会打印名字。为什么？因为  ES6 为**所有的函数**添加了 name 属性。当把匿名函数赋值给一个变量，那么这个变量名就会赋值给函数的 name 属性。

ES6 下运行：

```js
const foo = x => {};
console.log(foo.name) // ?
```

所举的例子没有说明箭头函数是词法绑定 this。

**Comment by lightningtgc** [comment]
THX @yanxyz 

首先，你说的第一个两个空格的间距可能是有点歧义，这里针对于箭头函数符号本身而言的，它与左右两边有一个空格，总共两个空格，存在有歧义的地方，可以接受统一的要求规范放在js规范中，ES6规范将删去此类约定。

其次，函数表达式存在提升问题，但不是关注的重点故没有体现出来，这一块属于ES3代码规范的范畴。

函数表达式是可以忽略函数名称，一般情况下会省略name，这一处需要再修改一下。

至于绑定this的demo需要再补充一下，也欢迎提PR上来。

希望能多给我们提出问题来改进，既然是开源的，也希望能多多探讨。感谢！

**Comment by yanxyz** [comment]
@lightningtgc 函数表达式存在提升问题，可否举个例子？
箭头函数的 this，[ES6 In Depth: Arrow functions](https://hacks.mozilla.org/2015/06/es6-in-depth-arrow-functions/) 举了个例子，常常我们需要在对象方法内 var self = this，以便用在内部函数内，使用箭头函数就不需要了。

**Comment by lightningtgc** [comment]
@yanxyz 昨晚已将您的建议修改提交到了master，附加了绑定this的栗子，hoist的问题也删除了，由js规范来约定，不放在此规范中

**Comment by yanxyz** [comment]
@lightningtgc 再补充一个

> 箭头函数中不能使用arguments对象

箭头函数它自己没有 arguments ，不过可以使用外部函数的 arguments:

```js
function test () {
  return () => arguments[0]
}

test(5)() // ?
```

**Comment by lightningtgc** [comment]
@yanxyz 可以理解，但是如此引用会引起一些编码时的误解，
我建议还是使用rest语法会让代码看起来更清晰一些,并且是个real array
```js
function test(...args) {
  return () => args[0];
}

test(5)() // ?
```

并且此时的arguments已不再是Arrows内部的概念了。

**Comment by yanxyz** [comment]
@lightningtgc 我只是举例说明那句话说法有歧义。至于怎么做，根据实际情况定。
